version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout 
      # Install via apk on alpine based images
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            echo 'Starting building docker image'
            docker build -t circlecidockerimage .
            echo 'Finished building docker image'