version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout 
      - setup_remote_docker
      # Install via apk on alpine based images
      #- run:
      #name: Install Docker client
      #command: apk update && apk add docker-cli
      - run:
          name: Build docker image
          command: |
            echo 'Starting building docker image'
            docker build -t circlecidockerimage .
            echo 'Finished building docker image'
workflows: 
  version: 2
  testworkflow:
    jobs: 
      - build:
          filters:
              branches:
                only: master